// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001122451_InitialFullSeed")]
    partial class InitialFullSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Kem, xúc xích đông lạnh, chả giò"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thực phẩm tươi sống",
                            Description = "Thịt, hải sản, rau củ quả tươi"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Gạo & Các loại hạt",
                            Description = "Gạo tẻ, gạo lứt, hạt ngũ cốc"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Mỹ phẩm & Chăm sóc cá nhân",
                            Description = "Sữa tắm, dầu gội, kem đánh răng"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Chăm sóc nhà cửa",
                            Description = "Nước lau sàn, nước rửa chén, bột giặt"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Mẹ & Bé",
                            Description = "Sữa bột, tã bỉm, đồ chơi trẻ em"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Chăm sóc sức khỏe",
                            Description = "Khẩu trang, vitamin, băng cá nhân"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ dùng gia đình",
                            Description = "Khăn giấy, màng bọc thực phẩm, ly nhựa"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút, tập vở, giấy in, kéo"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Thức ăn thú cưng",
                            Description = "Thức ăn hạt, pate cho chó mèo"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerName = "Phạm Hoàng D",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0934567890",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerName = "Hoàng Thị E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0976543210",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 6,
                            CustomerName = "Đỗ Minh F",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909123456",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 7,
                            CustomerName = "Vũ Thị G",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0912345678",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 8,
                            CustomerName = "Bùi Văn H",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 9,
                            CustomerName = "Đặng Thị I",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0945678901",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 10,
                            CustomerName = "Ngoạn Văn K",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0923456789",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 11,
                            CustomerName = "Dương Thi L",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0961234567",
                            RewardPoints = 5
                        },
                        new
                        {
                            CustomerId = 12,
                            CustomerName = "Lý Văn M",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0931122334",
                            RewardPoints = 600
                        },
                        new
                        {
                            CustomerId = 13,
                            CustomerName = "Ngô Thị N",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0971122334",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 14,
                            CustomerName = "Trịnh Văn O",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0908877665",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 15,
                            CustomerName = "Đoàn Thị P",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0919988776",
                            RewardPoints = 310
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8930000000011",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Snack khoai tây vị tự nhiên 50g",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8930000000028",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Bánh quy bơ 150g",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8930000000035",
                            CategoryId = 1,
                            Price = 18000m,
                            ProductName = "Kẹo dẻo trái cây 100g",
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8930000000042",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước ngọt có ga lon 330ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8930000000059",
                            CategoryId = 2,
                            Price = 6000m,
                            ProductName = "Nước khoáng chai 500ml",
                            StockQuantity = 250
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8930000000066",
                            CategoryId = 2,
                            Price = 12000m,
                            ProductName = "Trà xanh đóng chai 455ml",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8930000000073",
                            CategoryId = 3,
                            Price = 32000m,
                            ProductName = "Sữa tươi tiệt trùng hộp 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8930000000080",
                            CategoryId = 3,
                            Price = 8000m,
                            ProductName = "Sữa chua uống men sống 100ml",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8930000000097",
                            CategoryId = 3,
                            Price = 38000m,
                            ProductName = "Phô mai lát 140g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8930000000103",
                            CategoryId = 4,
                            Price = 5000m,
                            ProductName = "Mì gói tôm chua cay 75g",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8930000000110",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Phở bò ăn liền 65g",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8930000000127",
                            CategoryId = 4,
                            Price = 7000m,
                            ProductName = "Cháo gói thịt bằm 50g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8930000000134",
                            CategoryId = 5,
                            Price = 45000m,
                            ProductName = "Nước mắm cá cơm 500ml",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8930000000141",
                            CategoryId = 5,
                            Price = 38000m,
                            ProductName = "Hạt nêm thịt thăn 400g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8930000000158",
                            CategoryId = 5,
                            Price = 55000m,
                            ProductName = "Dầu ăn thực vật chai 1L",
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
