// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008123009_lan16")]
    partial class lan16
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước suối, nước tăng lực, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sữa và sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, sữa hộp, phô mai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bánh kẹo và snack",
                            Description = "Bánh quy, snack khoai tây, kẹo, chocolate"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì, phở, cháo ăn liền",
                            Description = "Mì gói, mì ly, phở và cháo ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Cơm hộp và món ăn sẵn",
                            Description = "Cơm hộp, cơm cuộn, xôi, món ăn hâm nóng tại quầy"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Bánh mì và bánh tươi",
                            Description = "Bánh mì, sandwich, bánh bao, bánh ngọt trong ngày"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Kem và thực phẩm đông lạnh",
                            Description = "Kem ốc quế, xúc xích, cá viên và món chiên đông lạnh"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cà phê và trà",
                            Description = "Cà phê lon, cà phê hòa tan, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Gia vị và thực phẩm khô",
                            Description = "Nước mắm, dầu ăn, đường, gia vị đóng gói nhỏ"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ hộp và thực phẩm đóng gói",
                            Description = "Cá hộp, pate, rong biển ăn liền, thực phẩm đóng gói"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Trái cây và rau củ tiện lợi",
                            Description = "Trái cây tươi, trái cây cắt sẵn, salad đóng hộp"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Kem đánh răng, dầu gội, sữa tắm, khăn ướt"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ gia dụng và vệ sinh",
                            Description = "Khăn giấy, túi rác, nước rửa chén, vật dụng sinh hoạt"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút, vở, băng keo và dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Phụ kiện tiện ích",
                            Description = "Pin, cáp sạc, khẩu trang và phụ kiện dùng nhanh"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "18 Nguyễn Huệ, Phường Sài Gòn, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000001",
                            RewardPoints = 850
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Lê Thánh Tôn, Phường Sài Gòn, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000002",
                            RewardPoints = 420
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "120 Phạm Ngũ Lão, Phường Bến Thành, TP. Hồ Chí Minh",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000003",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "62 Bùi Viện, Phường Bến Thành, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000004",
                            RewardPoints = 720
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "160 Nguyễn Trãi, Phường Bến Thành, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Văn Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000005",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "75 Nguyễn Thái Học, Phường Cầu Ông Lãnh, TP. Hồ Chí Minh",
                            CustomerName = "Võ Thị Hạnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000006",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "30 Cô Giang, Phường Cầu Ông Lãnh, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Minh Hoàng",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000007",
                            RewardPoints = 480
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "27 Trần Quang Khải, Phường Tân Định, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Thị Lan",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000008",
                            RewardPoints = 920
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "95 Nguyễn Văn Nguyễn, Phường Tân Định, TP. Hồ Chí Minh",
                            CustomerName = "Ngô Văn Minh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000009",
                            RewardPoints = 160
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "38 Tôn Thất Thuyết, Phường Vĩnh Hội, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Thị Ngọc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000010",
                            RewardPoints = 390
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "220 Hoàng Diệu, Phường Khánh Hội, TP. Hồ Chí Minh",
                            CustomerName = "Phan Văn Phúc",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000011",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "346 Quang Trung, Phường Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Thị Quỳnh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000012",
                            RewardPoints = 780
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "88 Võ Văn Ngân, Phường Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Trương Văn Sơn",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000013",
                            RewardPoints = 510
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "15 Lê Văn Thọ, Phường Thông Tây Hội, TP. Hồ Chí Minh",
                            CustomerName = "Lý Thị Thảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000014",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "212 Nguyễn Hữu Cảnh, Phường Thạnh Mỹ Tây, TP. Hồ Chí Minh",
                            CustomerName = "Mai Văn Thành",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000015",
                            RewardPoints = 440
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "85 Xô Viết Nghệ Tĩnh, Phường Thạnh Mỹ Tây, TP. Hồ Chí Minh",
                            CustomerName = "Huỳnh Thị Uyên",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000016",
                            RewardPoints = 1100
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "40 Phan Xích Long, Phường Cầu Kiệu, TP. Hồ Chí Minh",
                            CustomerName = "Dương Văn Việt",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000017",
                            RewardPoints = 130
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "150 Hoàng Văn Thụ, Phường Tân Sơn Nhất, TP. Hồ Chí Minh",
                            CustomerName = "Phan Thị Xuân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000018",
                            RewardPoints = 560
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "55 Huỳnh Tấn Phát, Phường Tân Thuận, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Quốc Anh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000019",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "120 Lê Văn Việt, Phường Tăng Nhơn Phú, TP. Hồ Chí Minh",
                            CustomerName = "Trần Minh Khoa",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000020",
                            RewardPoints = 950
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8930000000011",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Nước ngọt Coca-Cola lon 330ml",
                            StockQuantity = 240
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8930000000028",
                            CategoryId = 1,
                            Price = 11000m,
                            ProductName = "Nước tăng lực Number 1 chai 330ml",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8930000000035",
                            CategoryId = 1,
                            Price = 6000m,
                            ProductName = "Nước suối Aquafina chai 500ml",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8930000000042",
                            CategoryId = 2,
                            Price = 36000m,
                            ProductName = "Sữa tươi Vinamilk 100% hộp 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8930000000059",
                            CategoryId = 2,
                            Price = 8000m,
                            ProductName = "Sữa chua Vinamilk có đường hộp 100g",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8930000000066",
                            CategoryId = 2,
                            Price = 9000m,
                            ProductName = "Sữa tươi TH true MILK hộp 180ml",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8930000000073",
                            CategoryId = 3,
                            Price = 14000m,
                            ProductName = "Snack khoai tây Lay's vị tự nhiên 52g",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8930000000080",
                            CategoryId = 3,
                            Price = 24000m,
                            ProductName = "Bánh quy Oreo vani 133g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8930000000097",
                            CategoryId = 3,
                            Price = 18000m,
                            ProductName = "Chocolate KitKat 4 thanh 35g",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8930000000103",
                            CategoryId = 4,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo tôm chua cay gói 75g",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8930000000110",
                            CategoryId = 4,
                            Price = 12000m,
                            ProductName = "Mì ly Modern lẩu thái 65g",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8930000000127",
                            CategoryId = 4,
                            Price = 11000m,
                            ProductName = "Phở bò Vifon ăn liền gói 65g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8930000000134",
                            CategoryId = 5,
                            Price = 35000m,
                            ProductName = "Cơm hộp gà teriyaki 300g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8930000000141",
                            CategoryId = 5,
                            Price = 25000m,
                            ProductName = "Cơm cuộn rong biển (kimbap) 200g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8930000000158",
                            CategoryId = 5,
                            Price = 20000m,
                            ProductName = "Xôi mặn gói 150g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8930000000165",
                            CategoryId = 6,
                            Price = 20000m,
                            ProductName = "Bánh mì thịt nguội",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8930000000172",
                            CategoryId = 6,
                            Price = 25000m,
                            ProductName = "Sandwich gà phô mai",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8930000000189",
                            CategoryId = 6,
                            Price = 18000m,
                            ProductName = "Bánh bao nhân thịt trứng cút",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8930000000196",
                            CategoryId = 7,
                            Price = 22000m,
                            ProductName = "Kem ốc quế Cornetto vị chocolate",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8930000000202",
                            CategoryId = 7,
                            Price = 15000m,
                            ProductName = "Xúc xích nướng que hâm nóng",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "8930000000219",
                            CategoryId = 7,
                            Price = 52000m,
                            ProductName = "Cá viên chiên đông lạnh 500g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "8930000000226",
                            CategoryId = 8,
                            Price = 12000m,
                            ProductName = "Cà phê sữa NESCAFÉ lon 170ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "8930000000233",
                            CategoryId = 8,
                            Price = 48000m,
                            ProductName = "Cà phê hòa tan G7 3in1 hộp 16 gói",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "8930000000240",
                            CategoryId = 8,
                            Price = 11000m,
                            ProductName = "Trà xanh Không Độ chai 455ml",
                            StockQuantity = 130
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "8930000000257",
                            CategoryId = 9,
                            Price = 45000m,
                            ProductName = "Nước mắm Nam Ngư chai 500ml",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "8930000000264",
                            CategoryId = 9,
                            Price = 58000m,
                            ProductName = "Dầu ăn Neptune 1L",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "8930000000271",
                            CategoryId = 9,
                            Price = 26000m,
                            ProductName = "Đường tinh luyện 1kg",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "8930000000288",
                            CategoryId = 10,
                            Price = 35000m,
                            ProductName = "Cá ngừ ngâm dầu Hạ Long 185g",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "8930000000295",
                            CategoryId = 10,
                            Price = 30000m,
                            ProductName = "Pate gan Hạ Long hộp 150g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "8930000000301",
                            CategoryId = 10,
                            Price = 8000m,
                            ProductName = "Rong biển sấy giòn ăn liền 5g",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 31,
                            Barcode = "8930000000318",
                            CategoryId = 11,
                            Price = 32000m,
                            ProductName = "Chuối tiêu 1kg",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 32,
                            Barcode = "8930000000325",
                            CategoryId = 11,
                            Price = 30000m,
                            ProductName = "Trái cây cắt sẵn hộp 250g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 33,
                            Barcode = "8930000000332",
                            CategoryId = 11,
                            Price = 28000m,
                            ProductName = "Salad rau trộn hộp 200g",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 34,
                            Barcode = "8930000000349",
                            CategoryId = 12,
                            Price = 34000m,
                            ProductName = "Kem đánh răng P/S 180g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 35,
                            Barcode = "8930000000356",
                            CategoryId = 12,
                            Price = 38000m,
                            ProductName = "Dầu gội Sunsilk chai 170g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 36,
                            Barcode = "8930000000363",
                            CategoryId = 12,
                            Price = 15000m,
                            ProductName = "Khăn ướt Mama gói 20 tờ",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 37,
                            Barcode = "8930000000370",
                            CategoryId = 13,
                            Price = 22000m,
                            ProductName = "Khăn giấy rút Pulppy 100 tờ",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 38,
                            Barcode = "8930000000387",
                            CategoryId = 13,
                            Price = 38000m,
                            ProductName = "Nước rửa chén Sunlight chai 750ml",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 39,
                            Barcode = "8930000000394",
                            CategoryId = 13,
                            Price = 25000m,
                            ProductName = "Túi rác đen tự hủy cuộn 1kg",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 40,
                            Barcode = "8930000000400",
                            CategoryId = 14,
                            Price = 5000m,
                            ProductName = "Bút bi Thiên Long TL-027 xanh",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 41,
                            Barcode = "8930000000417",
                            CategoryId = 14,
                            Price = 14000m,
                            ProductName = "Vở Campus 96 trang",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 42,
                            Barcode = "8930000000424",
                            CategoryId = 14,
                            Price = 8000m,
                            ProductName = "Băng keo trong 2.4cm",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 43,
                            Barcode = "8930000000431",
                            CategoryId = 15,
                            Price = 28000m,
                            ProductName = "Pin AA Panasonic vỉ 2 viên",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 44,
                            Barcode = "8930000000448",
                            CategoryId = 15,
                            Price = 69000m,
                            ProductName = "Cáp sạc USB-C 1m",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 45,
                            Barcode = "8930000000455",
                            CategoryId = 15,
                            Price = 18000m,
                            ProductName = "Khẩu trang y tế 4 lớp hộp 10 cái",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Nguyễn Quản Trị",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin01"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Trần Giám Đốc",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin02"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Lê Thu Ngân",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier01"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Phạm Bán Hàng",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier02"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Hoàng Thu Ngân",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier03"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Vũ Thị Quầy",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier04"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Đỗ Bán Lẻ",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier05"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Ngô Quản Kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware01"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Bùi Kiểm Kê",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware02"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Dương Thủ Kho",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware03"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Lý Nhập Hàng",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware04"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Đặng Hỗ Trợ",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin_backup"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Hồ Ca Chiều",
                            IsActive = true,
                            Password = "123456",
                            Role = "Cashier",
                            Username = "cashier06"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Trương Vận Chuyển",
                            IsActive = true,
                            Password = "123456",
                            Role = "Warehouse",
                            Username = "ware05"
                        },
                        new
                        {
                            Id = 15,
                            FullName = "Mai Giám Sát",
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "supervisor"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
