// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261007174705_chaylan1")]
    partial class chaylan1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước suối, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sữa và sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bánh kẹo",
                            Description = "Bánh quy, bánh ngọt, kẹo và đồ ăn vặt"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì và thực phẩm ăn liền",
                            Description = "Mì gói, phở, cháo và thực phẩm ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị và thực phẩm khô",
                            Description = "Nước mắm, dầu ăn, đường, muối, hạt nêm"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Đồ dùng cá nhân",
                            Description = "Dầu gội, sữa tắm, kem đánh răng"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ gia dụng",
                            Description = "Khăn giấy, túi rác, nước rửa chén"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ ăn nhanh",
                            Description = "Xúc xích, sandwich, cơm hộp và thực phẩm ăn liền"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901234567",
                            RewardPoints = 850
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Quận 3, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 420
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Lê Minh Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Quận 10, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0938123456",
                            RewardPoints = 1050
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Quận Tân Bình, TP.HCM",
                            CustomerName = "Hoàng Văn Em",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0978456123",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "TP. Thủ Đức, TP.HCM",
                            CustomerName = "Võ Thị Hà",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0967123456",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Quận Gò Vấp, TP.HCM",
                            CustomerName = "Đặng Quốc Huy",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0945678123",
                            RewardPoints = 720
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Nguyễn Thị Lan",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0923456789",
                            RewardPoints = 280
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938505970011",
                            CategoryId = 1,
                            Price = 6000m,
                            ProductName = "Nước suối Aquafina 500ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8935049500028",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Coca Cola lon 330ml",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8935049500035",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Pepsi lon 330ml",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8935049500042",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Sting dâu chai 330ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8935049500059",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Trà xanh 0 độ 455ml",
                            StockQuantity = 130
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8934673500066",
                            CategoryId = 2,
                            Price = 34000m,
                            ProductName = "Sữa tươi Vinamilk 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8934673500073",
                            CategoryId = 2,
                            Price = 8000m,
                            ProductName = "Sữa tươi Vinamilk ít đường 180ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8934673500080",
                            CategoryId = 2,
                            Price = 7000m,
                            ProductName = "Sữa chua Vinamilk có đường",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8934673500097",
                            CategoryId = 2,
                            Price = 9000m,
                            ProductName = "Sữa chua uống Probi",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8935001700103",
                            CategoryId = 3,
                            Price = 32000m,
                            ProductName = "Bánh quy bơ Danisa 90g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8935001700110",
                            CategoryId = 3,
                            Price = 38000m,
                            ProductName = "Bánh Chocopie hộp 6 cái",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8935001700127",
                            CategoryId = 3,
                            Price = 12000m,
                            ProductName = "Snack khoai tây vị tự nhiên",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8935001700134",
                            CategoryId = 3,
                            Price = 18000m,
                            ProductName = "Kẹo dẻo trái cây 100g",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8934563100141",
                            CategoryId = 4,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo tôm chua cay",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8934563100158",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Mì Omachi sườn hầm ngũ quả",
                            StockQuantity = 180
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8934563100165",
                            CategoryId = 4,
                            Price = 8000m,
                            ProductName = "Phở bò ăn liền",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8934563100172",
                            CategoryId = 4,
                            Price = 7000m,
                            ProductName = "Cháo thịt bằm ăn liền",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8934804100189",
                            CategoryId = 5,
                            Price = 42000m,
                            ProductName = "Nước mắm Nam Ngư 500ml",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8934804100196",
                            CategoryId = 5,
                            Price = 48000m,
                            ProductName = "Dầu ăn Neptune 1L",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8934804100202",
                            CategoryId = 5,
                            Price = 36000m,
                            ProductName = "Hạt nêm Knorr 400g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "8934804100219",
                            CategoryId = 5,
                            Price = 25000m,
                            ProductName = "Đường tinh luyện 1kg",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "8936002100226",
                            CategoryId = 6,
                            Price = 98000m,
                            ProductName = "Dầu gội Clear bạc hà 650g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "8936002100233",
                            CategoryId = 6,
                            Price = 85000m,
                            ProductName = "Sữa tắm Lifebuoy 527ml",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "8936002100240",
                            CategoryId = 6,
                            Price = 35000m,
                            ProductName = "Kem đánh răng P/S 180g",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "8936003100257",
                            CategoryId = 7,
                            Price = 28000m,
                            ProductName = "Khăn giấy hộp 180 tờ",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "8936003100264",
                            CategoryId = 7,
                            Price = 32000m,
                            ProductName = "Nước rửa chén Sunlight 750ml",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "8936003100271",
                            CategoryId = 7,
                            Price = 22000m,
                            ProductName = "Túi rác tự hủy cuộn 30 túi",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "8937004200288",
                            CategoryId = 8,
                            Price = 15000m,
                            ProductName = "Xúc xích tiệt trùng CP",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "8937004200295",
                            CategoryId = 8,
                            Price = 25000m,
                            ProductName = "Sandwich sandwich kẹp thịt",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "8937004200301",
                            CategoryId = 8,
                            Price = 35000m,
                            ProductName = "Cơm hộp gà teriyaki",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 31,
                            Barcode = "8937004200318",
                            CategoryId = 8,
                            Price = 20000m,
                            ProductName = "Bánh mì xúc xích",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 32,
                            Barcode = "8937004200325",
                            CategoryId = 8,
                            Price = 12000m,
                            ProductName = "Trứng luộc đóng hộp",
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
