// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008102040_InitialLan3")]
    partial class InitialLan3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước khoáng, nước trái cây"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sữa và sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bánh kẹo",
                            Description = "Bánh quy, bánh ngọt, kẹo các loại"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì và thực phẩm ăn liền",
                            Description = "Mì gói, phở, cháo và thực phẩm ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị và thực phẩm khô",
                            Description = "Nước mắm, dầu ăn, hạt nêm, đường"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Đồ dùng cá nhân",
                            Description = "Kem đánh răng, dầu gội, sữa tắm"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ gia dụng",
                            Description = "Đồ dùng gia đình và vật dụng sinh hoạt"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ ăn nhanh",
                            Description = "Xúc xích, sandwich, hamburger và đồ ăn nhanh"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Thực phẩm đông lạnh và đồ chế biến sẵn"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Trái cây",
                            Description = "Các loại trái cây tươi"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Rau củ",
                            Description = "Rau củ quả tươi"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Đồ hộp",
                            Description = "Cá hộp, thịt hộp và thực phẩm đóng hộp"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Cà phê và trà",
                            Description = "Cà phê, trà túi lọc và trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút, vở, giấy và dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Chăm sóc nhà cửa",
                            Description = "Nước giặt, nước rửa chén và chất tẩy rửa"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "12 Nguyễn Huệ, Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000001",
                            RewardPoints = 850
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "25 Lê Lợi, Quận 1, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000002",
                            RewardPoints = 420
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "38 Điện Biên Phủ, Bình Thạnh, TP.HCM",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000003",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "45 Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000004",
                            RewardPoints = 720
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "56 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM",
                            CustomerName = "Hoàng Văn Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000005",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "67 Cách Mạng Tháng 8, Quận 10, TP.HCM",
                            CustomerName = "Võ Thị Hạnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000006",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "78 Phan Văn Trị, Gò Vấp, TP.HCM",
                            CustomerName = "Đặng Minh Hoàng",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000007",
                            RewardPoints = 480
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "89 Quang Trung, Gò Vấp, TP.HCM",
                            CustomerName = "Bùi Thị Lan",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000008",
                            RewardPoints = 920
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "91 Lạc Long Quân, Tân Bình, TP.HCM",
                            CustomerName = "Ngô Văn Minh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000009",
                            RewardPoints = 160
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "102 Hoàng Văn Thụ, Tân Bình, TP.HCM",
                            CustomerName = "Đỗ Thị Ngọc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000010",
                            RewardPoints = 390
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "115 Âu Cơ, Tân Phú, TP.HCM",
                            CustomerName = "Phan Văn Phúc",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000011",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "126 Tân Kỳ Tân Quý, Tân Phú, TP.HCM",
                            CustomerName = "Nguyễn Thị Quỳnh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000012",
                            RewardPoints = 780
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "137 Nguyễn Oanh, Gò Vấp, TP.HCM",
                            CustomerName = "Trương Văn Sơn",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000013",
                            RewardPoints = 510
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "148 Phạm Văn Đồng, Thủ Đức, TP.HCM",
                            CustomerName = "Lý Thị Thảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000014",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "159 Võ Văn Ngân, Thủ Đức, TP.HCM",
                            CustomerName = "Mai Văn Thành",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000015",
                            RewardPoints = 440
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "162 Kha Vạn Cân, Thủ Đức, TP.HCM",
                            CustomerName = "Huỳnh Thị Uyên",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000016",
                            RewardPoints = 1100
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "173 Nguyễn Văn Luông, Quận 6, TP.HCM",
                            CustomerName = "Dương Văn Việt",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000017",
                            RewardPoints = 130
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "184 Hậu Giang, Quận 6, TP.HCM",
                            CustomerName = "Phan Thị Xuân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901000018",
                            RewardPoints = 560
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "195 Kinh Dương Vương, Bình Tân, TP.HCM",
                            CustomerName = "Nguyễn Quốc Anh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901000019",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "206 Tỉnh Lộ 10, Bình Tân, TP.HCM",
                            CustomerName = "Trần Minh Khoa",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901000020",
                            RewardPoints = 950
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8930000000011",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Nước ngọt Coca Cola lon 330ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8930000000028",
                            CategoryId = 1,
                            Price = 10000m,
                            ProductName = "Nước ngọt Pepsi lon 330ml",
                            StockQuantity = 180
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8930000000035",
                            CategoryId = 1,
                            Price = 6000m,
                            ProductName = "Nước khoáng Lavie chai 500ml",
                            StockQuantity = 250
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8930000000042",
                            CategoryId = 2,
                            Price = 32000m,
                            ProductName = "Sữa tươi Vinamilk 1L",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8930000000059",
                            CategoryId = 2,
                            Price = 7000m,
                            ProductName = "Sữa chua Vinamilk hộp",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8930000000066",
                            CategoryId = 2,
                            Price = 38000m,
                            ProductName = "Phô mai lát 140g",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8930000000073",
                            CategoryId = 3,
                            Price = 25000m,
                            ProductName = "Bánh quy bơ 150g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8930000000080",
                            CategoryId = 3,
                            Price = 18000m,
                            ProductName = "Bánh xốp chocolate 120g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8930000000097",
                            CategoryId = 3,
                            Price = 18000m,
                            ProductName = "Kẹo dẻo trái cây 100g",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8930000000103",
                            CategoryId = 4,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo tôm chua cay 75g",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8930000000110",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Mì Omachi sườn hầm ngũ quả",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8930000000127",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Phở bò ăn liền 65g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8930000000134",
                            CategoryId = 5,
                            Price = 45000m,
                            ProductName = "Nước mắm cá cơm 500ml",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8930000000141",
                            CategoryId = 5,
                            Price = 55000m,
                            ProductName = "Dầu ăn thực vật 1L",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8930000000158",
                            CategoryId = 5,
                            Price = 38000m,
                            ProductName = "Hạt nêm thịt thăn 400g",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "8930000000165",
                            CategoryId = 6,
                            Price = 32000m,
                            ProductName = "Kem đánh răng P/S 180g",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "8930000000172",
                            CategoryId = 6,
                            Price = 85000m,
                            ProductName = "Dầu gội Sunsilk 650g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "8930000000189",
                            CategoryId = 6,
                            Price = 90000m,
                            ProductName = "Sữa tắm Lifebuoy 800g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "8930000000196",
                            CategoryId = 7,
                            Price = 18000m,
                            ProductName = "Khăn giấy đa năng",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "8930000000202",
                            CategoryId = 7,
                            Price = 25000m,
                            ProductName = "Túi rác tự phân hủy",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "8930000000219",
                            CategoryId = 7,
                            Price = 35000m,
                            ProductName = "Hộp đựng thực phẩm 1L",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "8930000000226",
                            CategoryId = 8,
                            Price = 28000m,
                            ProductName = "Xúc xích tiệt trùng 175g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "8930000000233",
                            CategoryId = 8,
                            Price = 25000m,
                            ProductName = "Sandwich sandwich thịt nguội",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "8930000000240",
                            CategoryId = 8,
                            Price = 15000m,
                            ProductName = "Bánh bao nhân thịt",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "8930000000257",
                            CategoryId = 9,
                            Price = 45000m,
                            ProductName = "Cá viên chiên đông lạnh 500g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "8930000000264",
                            CategoryId = 9,
                            Price = 65000m,
                            ProductName = "Xúc xích Đức đông lạnh 500g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "8930000000271",
                            CategoryId = 9,
                            Price = 55000m,
                            ProductName = "Há cảo đông lạnh 300g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "8930000000288",
                            CategoryId = 10,
                            Price = 65000m,
                            ProductName = "Táo Fuji nhập khẩu 1kg",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "8930000000295",
                            CategoryId = 10,
                            Price = 30000m,
                            ProductName = "Chuối tiêu 1kg",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "8930000000301",
                            CategoryId = 10,
                            Price = 55000m,
                            ProductName = "Cam vàng 1kg",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 31,
                            Barcode = "8930000000318",
                            CategoryId = 11,
                            Price = 18000m,
                            ProductName = "Cà rốt Đà Lạt 500g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 32,
                            Barcode = "8930000000325",
                            CategoryId = 11,
                            Price = 28000m,
                            ProductName = "Khoai tây 1kg",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 33,
                            Barcode = "8930000000332",
                            CategoryId = 11,
                            Price = 15000m,
                            ProductName = "Rau cải xanh 500g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 34,
                            Barcode = "8930000000349",
                            CategoryId = 12,
                            Price = 32000m,
                            ProductName = "Cá ngừ đóng hộp 185g",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 35,
                            Barcode = "8930000000356",
                            CategoryId = 12,
                            Price = 35000m,
                            ProductName = "Thịt heo hầm đóng hộp 150g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 36,
                            Barcode = "8930000000363",
                            CategoryId = 12,
                            Price = 28000m,
                            ProductName = "Đậu Hà Lan đóng hộp 400g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 37,
                            Barcode = "8930000000370",
                            CategoryId = 13,
                            Price = 45000m,
                            ProductName = "Cà phê hòa tan 3in1",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 38,
                            Barcode = "8930000000387",
                            CategoryId = 13,
                            Price = 65000m,
                            ProductName = "Cà phê rang xay 250g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 39,
                            Barcode = "8930000000394",
                            CategoryId = 13,
                            Price = 38000m,
                            ProductName = "Trà túi lọc 25 gói",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 40,
                            Barcode = "8930000000400",
                            CategoryId = 14,
                            Price = 5000m,
                            ProductName = "Bút bi xanh Thiên Long",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 41,
                            Barcode = "8930000000417",
                            CategoryId = 14,
                            Price = 18000m,
                            ProductName = "Vở học sinh 200 trang",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 42,
                            Barcode = "8930000000424",
                            CategoryId = 14,
                            Price = 4000m,
                            ProductName = "Bút chì HB",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 43,
                            Barcode = "8930000000431",
                            CategoryId = 15,
                            Price = 32000m,
                            ProductName = "Nước rửa chén Sunlight 750ml",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 44,
                            Barcode = "8930000000448",
                            CategoryId = 15,
                            Price = 125000m,
                            ProductName = "Nước giặt OMO 2.6kg",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 45,
                            Barcode = "8930000000455",
                            CategoryId = 15,
                            Price = 45000m,
                            ProductName = "Nước lau sàn 1L",
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
